<a href="https://colab.research.google.com/github/mehdiiiii786/Mhdii-learning-ML-/blob/main/ML_Logistic_REG_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

In [47]:
df = pd.read_csv('/content/spam.csv', encoding='latin1')
df

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:57: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(column, errors="raise")


v1  ... Unnamed: 4
0      ham  ...        NaN
1      ham  ...        NaN
2     spam  ...        NaN
3      ham  ...        NaN
4      ham  ...        NaN
...    ...  ...        ...
5567  spam  ...        NaN
5568   ham  ...        NaN
5569   ham  ...        NaN
5570   ham  ...        NaN
5571   ham  ...        NaN

[5572 rows x 5 columns]

In [48]:
df = df[['v1','v2']]
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [49]:
df.columns= ['Label', 'message']

In [50]:
df

Label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [51]:
df.isnull().sum()

Label      0
message    0
dtype: int64

In [52]:
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(df['message'])

In [53]:
print(vectorizer.get_feature_names_out())

['00' '000' '000pes' ... 'ûïharry' 'ûò' 'ûówell']


In [54]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 73916 stored elements and shape (5572, 8672)>
  Coords	Values
  (0, 3550)	1
  (0, 8030)	1
  (0, 4350)	1
  (0, 5920)	1
  (0, 2327)	1
  (0, 1303)	1
  (0, 5537)	1
  (0, 4087)	1
  (0, 1751)	1
  (0, 3634)	1
  (0, 8489)	1
  (0, 4476)	1
  (0, 1749)	1
  (0, 2048)	1
  (0, 7645)	1
  (0, 3594)	1
  (0, 1069)	1
  (0, 8267)	1
  (1, 5504)	1
  (1, 4512)	1
  (1, 4318)	1
  (1, 8392)	1
  (1, 5533)	1
  (2, 4087)	1
  (2, 3358)	1
  :	:
  (5570, 4218)	1
  (5570, 8313)	1
  (5570, 1084)	1
  (5570, 4615)	1
  (5570, 7039)	1
  (5570, 3308)	1
  (5570, 7627)	1
  (5570, 1438)	1
  (5570, 5334)	1
  (5570, 2592)	1
  (5570, 8065)	1
  (5570, 1778)	1
  (5570, 7049)	1
  (5570, 2892)	1
  (5570, 3470)	1
  (5570, 1786)	1
  (5570, 3687)	1
  (5570, 4161)	1
  (5570, 903)	1
  (5570, 1546)	1
  (5571, 7756)	1
  (5571, 5244)	1
  (5571, 4225)	2
  (5571, 7885)	1
  (5571, 6505)	1


In [55]:
le = LabelEncoder()
df['label_num'] = le.fit_transform(df['Label'])

In [56]:
y = df['label_num']


In [57]:
y = np.asarray(y)

In [58]:
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 73916 stored elements and shape (5572, 8672)>

In [62]:
print(x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [64]:
x_dense = x.toarray()

x_norm = StandardScaler().fit_transform(x_dense)

In [65]:
x_norm

array([[-0.04240182, -0.06778458, -0.0133978 , ..., -0.0133978 ,
        -0.0263195 , -0.0133978 ],
       [-0.04240182, -0.06778458, -0.0133978 , ..., -0.0133978 ,
        -0.0263195 , -0.0133978 ],
       [-0.04240182, -0.06778458, -0.0133978 , ..., -0.0133978 ,
        -0.0263195 , -0.0133978 ],
       ...,
       [-0.04240182, -0.06778458, -0.0133978 , ..., -0.0133978 ,
        -0.0263195 , -0.0133978 ],
       [-0.04240182, -0.06778458, -0.0133978 , ..., -0.0133978 ,
        -0.0263195 , -0.0133978 ],
       [-0.04240182, -0.06778458, -0.0133978 , ..., -0.0133978 ,
        -0.0263195 , -0.0133978 ]])

In [66]:
x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=0.2, random_state= 4)

In [67]:
LR = LogisticRegression().fit(x_train, y_train)


In [68]:
yhat_prob = LR.predict_proba(x_test)

In [69]:
yhat_prob

array([[9.79559716e-01, 2.04402840e-02],
       [9.99833830e-01, 1.66169507e-04],
       [1.42507907e-05, 9.99985749e-01],
       ...,
       [2.54121703e-01, 7.45878297e-01],
       [5.08618036e-02, 9.49138196e-01],
       [3.36641657e-01, 6.63358343e-01]])

In [70]:
log_loss(y_test, yhat_prob)

0.1123878796662561

In [73]:
ndf = pd.DataFrame({'True': y_test, 'Predicted_Spam_Prob': yhat_prob[:, 1]})

In [74]:
ndf

True  Predicted_Spam_Prob
0        0             0.020440
1        0             0.000166
2        1             0.999986
3        0             0.000099
4        0             0.000157
...    ...                  ...
1110     0             0.174015
1111     0             0.000666
1112     0             0.745878
1113     1             0.949138
1114     1             0.663358

[1115 rows x 2 columns]