<a href="https://colab.research.google.com/github/mehdiiiii786/Mhdii-learning-ML-/blob/main/ML_Logistic_REG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss

In [3]:
df = pd.read_csv('/content/Book3.csv')

In [4]:
df

x1   x2  y
0     -169  268  1
1      124  498  1
2      618  279  1
3      377 -309  1
4     -457  307  0
...    ...  ... ..
10495  785 -410  1
10496  491 -298  1
10497  405  -32  1
10498  -26  224  1
10499  382  237  1

[10500 rows x 3 columns]

In [6]:
newdf = df.head(20)
newdf

x1   x2  y
0  -169  268  1
1   124  498  1
2   618  279  1
3   377 -309  1
4  -457  307  0
5   801 -187  1
6   907  123  1
7   836  155  1
8  -504 -481  0
9   -96  404  1
10  407  212  1
11  634  438  1
12 -944  426  0
13  770 -313  1
14 -252 -268  0
15  671  110  1
16  -52 -189  0
17 -928   67  0
18  908  314  1
19 -848  -71  0

In [10]:
x = np.asarray(newdf[['x1','x2']])
x

array([[-169,  268],
       [ 124,  498],
       [ 618,  279],
       [ 377, -309],
       [-457,  307],
       [ 801, -187],
       [ 907,  123],
       [ 836,  155],
       [-504, -481],
       [ -96,  404],
       [ 407,  212],
       [ 634,  438],
       [-944,  426],
       [ 770, -313],
       [-252, -268],
       [ 671,  110],
       [ -52, -189],
       [-928,   67],
       [ 908,  314],
       [-848,  -71]])

In [12]:
y = np.asarray(newdf[['y']])
y

array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0]])

In [14]:
x_norm = StandardScaler().fit(x).transform(x)
x_norm

array([[-0.49556958,  0.6243527 ],
       [-0.02588856,  1.42726644],
       [ 0.76599684,  0.66275292],
       [ 0.37967218, -1.38991349],
       [-0.95723556,  0.76049894],
       [ 1.05934709, -0.96402012],
       [ 1.22926582,  0.11816796],
       [ 1.11545233,  0.22987769],
       [-1.03257688, -1.99035333],
       [-0.37855007,  1.09911908],
       [ 0.42776238,  0.42886066],
       [ 0.79164495,  1.21781068],
       [-1.7378999 ,  1.17591953],
       [ 1.00965388, -1.40387721],
       [-0.62861915, -1.24678539],
       [ 0.8509562 ,  0.07278588],
       [-0.30801777, -0.97100198],
       [-1.71225179, -0.07732408],
       [ 1.23086883,  0.78493545],
       [-1.58401124, -0.55907232]])

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x_norm,y , test_size=0.2, random_state=4)

In [17]:
LR = LogisticRegression().fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [20]:
yhat = LR.predict(x_test)
yhat

array([0, 1, 1, 1])

In [22]:
yhat_prob = LR.predict_proba(x_test)
yhat_prob

array([[0.90552646, 0.09447354],
       [0.39736784, 0.60263216],
       [0.02973512, 0.97026488],
       [0.04831249, 0.95168751]])

In [24]:
log_loss(yhat,yhat_prob)

0.171347944633985