<a href="https://colab.research.google.com/github/mehdiiiii786/Mhdii-learning-ML-/blob/main/ML_Logistic_REG_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv('/content/hearing_test.csv')
df

age  physical_score  test_result
0     33.0            40.7            1
1     50.0            37.2            1
2     52.0            24.7            0
3     56.0            31.0            0
4     35.0            42.9            1
...    ...             ...          ...
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

[5000 rows x 3 columns]

In [4]:
newdf = df.head(20)
newdf

age  physical_score  test_result
0   33.0            40.7            1
1   50.0            37.2            1
2   52.0            24.7            0
3   56.0            31.0            0
4   35.0            42.9            1
5   58.0            23.0            0
6   66.0            28.9            0
7   38.0            41.1            1
8   53.0            32.0            0
9   43.0            41.5            1
10  39.0            42.1            1
11  58.0            31.3            1
12  45.0            39.8            1
13  52.0            34.6            1
14  36.0            43.0            1
15  83.0            10.7            0
16  57.0            32.9            0
17  39.0            40.7            1
18  58.0            26.8            0
19  54.0            36.2            1

In [5]:
x = np.asarray(newdf[['age', 'physical_score']])
x

array([[33. , 40.7],
       [50. , 37.2],
       [52. , 24.7],
       [56. , 31. ],
       [35. , 42.9],
       [58. , 23. ],
       [66. , 28.9],
       [38. , 41.1],
       [53. , 32. ],
       [43. , 41.5],
       [39. , 42.1],
       [58. , 31.3],
       [45. , 39.8],
       [52. , 34.6],
       [36. , 43. ],
       [83. , 10.7],
       [57. , 32.9],
       [39. , 40.7],
       [58. , 26.8],
       [54. , 36.2]])

In [6]:
y= np.asarray(newdf[['test_result']])
y

array([[1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1]])

In [7]:
x_norm = StandardScaler().fit(x).transform(x)
x_norm

array([[-1.45174713,  0.81763037],
       [-0.02103981,  0.38697479],
       [ 0.14727869, -1.15108082],
       [ 0.48391571, -0.37590079],
       [-1.28342862,  1.08832816],
       [ 0.65223422, -1.36025639],
       [ 1.32550825, -0.63429414],
       [-1.03095086,  0.86684815],
       [ 0.23143795, -0.25285634],
       [-0.61015459,  0.91606593],
       [-0.9467916 ,  0.9898926 ],
       [ 0.65223422, -0.33898746],
       [-0.44183608,  0.70689036],
       [ 0.14727869,  0.06705922],
       [-1.19926937,  1.1006326 ],
       [ 2.75621556, -2.87370312],
       [ 0.56807496, -0.14211634],
       [-0.9467916 ,  0.81763037],
       [ 0.65223422, -0.89268748],
       [ 0.3155972 ,  0.26393034]])

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x_norm,y, test_size=0.2, random_state=0)

In [11]:
LR = LogisticRegression().fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
yhat = LR.predict(x_test)
yhat

array([0, 1, 1, 1])

In [17]:
yhat_prob = LR.predict_proba(x_test)
yhat_prob

array([[0.74953135, 0.25046865],
       [0.25079296, 0.74920704],
       [0.34775982, 0.65224018],
       [0.4805043 , 0.5194957 ]])

In [18]:
log_loss(yhat,yhat_prob)

0.4148215526305208